
FROM python:3.8-slim


WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir pandas

# Run the task when the container launches
CMD ["python", "main.py"]
